name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Validate version format
        run: |
          if ! echo "${{ inputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Version must be in format x.y.z (e.g., 1.2.3)"
            exit 1
          fi
      
      - name: Check if version already exists
        run: |
          if git tag | grep -q "^${{ inputs.version }}$"; then
            echo "Error: Version ${{ inputs.version }} already exists"
            exit 1
          fi
      
      - name: Create version bump branch
        run: |
          git checkout -b version-bump-${{ inputs.version }}
      
      - name: Update version in files
        run: |
          # Create or update VERSION file
          echo "${{ inputs.version }}" > VERSION
          git add VERSION
          
          # If there are other files that need version updates, add them here
          # For example, if you have a version constant in Go code:
          # sed -i 's/const Version = ".*"/const Version = "${{ inputs.version }}"/' internal/version/version.go
      
      - name: Commit changes
        run: |
          git commit -m "bump version to ${{ inputs.version }}

          🤖 Generated with [Claude Code](https://claude.ai/code)

          Co-Authored-By: Claude <noreply@anthropic.com>"
      
      - name: Push branch
        run: |
          git push origin version-bump-${{ inputs.version }}
      
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Bump version to ${{ inputs.version }}" \
            --body "$(cat <<'EOF'
          ## Summary
          - Bump version to ${{ inputs.version }}
          
          ## Changes
          - Updated VERSION file
          
          This PR was created automatically by the bump-version workflow.
          When merged, this will trigger the tag-release workflow to create the git tag and release.
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          EOF
          )" \
            --base main \
            --head version-bump-${{ inputs.version }}