name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Validate version format
        run: |
          if ! echo "${{ inputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Version must be in format x.y.z (e.g., 1.2.3)"
            exit 1
          fi

      - name: Check if version already exists
        run: |
          if git tag | grep -q "^${{ inputs.version }}$"; then
            echo "Error: Version ${{ inputs.version }} already exists"
            exit 1
          fi

      - name: Create and push tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
          echo "Created and pushed tag: ${{ inputs.version }}"

      - name: Verify tag creation
        run: |
          echo "Tag created successfully! This will now trigger the release workflow."
          echo "Release workflow should start building for tag: ${{ inputs.version }}"
